/*
 * Manual integration test to verify the plugin behavior in a real build.
 *
 * Prerequisites:
 *   ./gradlew clean publishToMavenLocal
 *
 * Usage:
 *   Change digits in versioning block
 *   ./gradlew -b build-test.gradle clean
 *   ./gradlew -b build-test.gradle build
 *   ./gradlew -b build-test.gradle jar grabverRelease
 *
 * Then check version.properties to verify the results.
 */
plugins {
    id 'java'
    id 'eu.davidea.grabver' version '2.1.0'
}

repositories {
    mavenLocal()
}

// Shows DEBUG logs
defaultTasks('grabverVerbose')

versioning {
    major 1
    minor 2
    //preRelease "RC2"
    incrementBuild true
    incrementOn "deploy"
    saveOn "deploy"
}

println("TEST - VersionCode: ${versioning.code}")
println("TEST - VersionName: ${versioning.name}")
println("TEST - FullName: ${versioning.fullName}")
