plugins {
    id 'java'
    id 'eu.davidea.grabver'
}

versioning {
    major 2
    minor 2
    incrementBuild false
}
defaultTasks('grabverDebug')

println("MODULE_B - VersionCode: ${versioning.code}")
println("MODULE_B - VersionName: ${versioning.name}")
println("MODULE_B - FullName: ${versioning.fullName}")
